"""Score combination and transparency labels."""

from __future__ import annotations

from dataclasses import dataclass


GROQ_WEIGHT = 0.65
STYLOMETRIC_WEIGHT = 0.35
HUMAN_MAX = 0.30
AI_MIN = 0.80

AI_LABEL = (
    "AI attribution likely: This content shows strong signals associated with "
    "AI-generated writing. This is an estimate, not proof, and the creator may appeal."
)
HUMAN_LABEL = (
    "Human attribution likely: This content shows strong signals associated with "
    "human-written work. This is an estimate, not proof."
)
UNCERTAIN_LABEL = (
    "Attribution uncertain: The available signals do not clearly indicate whether "
    "this content was written by a human or generated by AI. No definitive "
    "attribution should be assumed."
)


@dataclass(frozen=True)
class Decision:
    attribution: str
    ai_likelihood: float
    confidence: float
    label: str


def _clamp(value: float) -> float:
    return max(0.0, min(1.0, float(value)))


def combine_scores(groq_score: float, stylometric_score: float) -> float:
    """Combine independent 0..1 AI-likelihood scores."""
    g = _clamp(groq_score)
    s = _clamp(stylometric_score)
    return round((g * GROQ_WEIGHT) + (s * STYLOMETRIC_WEIGHT), 4)


def decide(ai_likelihood: float) -> Decision:
    """Map AI likelihood to a category, confidence, and exact label text.

    Confidence is distance from the 0.5 uncertainty midpoint, scaled to 0..1.
    This makes 0.51 meaningfully low-confidence and 0.95 high-confidence.
    """
    score = _clamp(ai_likelihood)
    confidence = round(abs(score - 0.5) * 2.0, 4)

    if score >= AI_MIN:
        return Decision("likely_ai", round(score, 4), confidence, AI_LABEL)
    if score <= HUMAN_MAX:
        return Decision("likely_human", round(score, 4), confidence, HUMAN_LABEL)
    return Decision("uncertain", round(score, 4), confidence, UNCERTAIN_LABEL)
